apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name | default "newpod" | quote }}
  namespace: {{ .Values.namespace | default "default" | quote }}
  labels:
    app: {{ .Values.name | default "newpod" | quote }} 
spec:
  containers:
    - name: {{ .Values.name | default "newpod" | quote }} 
      image: "ghcr.io/newpod/newpod:v0.2.0"
      ports:
        - containerPort: 8943
